### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by pacien** [jtdaugherty/tart#10]
The tart package doesn't build on some distributions like Nix/NixOS because of some dependency incompatibility, resolved in issues #8 and #9. A new Hackage release would help.

**Comment by jtdaugherty** [comment]
Done! http://hackage.haskell.org/package/tart-0.2

**Comment by SenchoPens** [comment]
Hi! Tart does not build on NixOS because of vty upperbound, but I see you removed it 10 days ago, so can you please make a new Hackage release?
