### ISSUE TITLE
README uses the 'legacy v1 style' of cabal usage

### ISSUE THREAD

**Issue by LoganDark** [jtdaugherty/tart#14]
I'm not sure if this is a cabal issue or a readme issue, but running `cabal new-build` gave me this error:

```
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal update' to download it.
Resolving dependencies...
cabal: Could not resolve dependencies:
```

So I tried running `cabal update` and got this warning:

```
Warning: The update command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-update command or the legacy v1-update alias as new-style projects will become the default in the next version of cabal-install. Please file a bug if you cannot replicate a working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild
```

**Comment by jtdaugherty** [comment]
Yeah, even cabal itself is not consistent across versions about whether this is considered legacy usage. You can just run `cabal new-update` to get your package index downloaded. I'm actually going to update the README to just not mention the update step, since that's assumed. Thanks for reporting this!

**Comment by LoganDark** [comment]
> I'm actually going to update the README to just not mention the update step, since that's assumed.

Actually I didn't even look at that part of the readme, and only looked at what `cabal new-build` told me to do. In that case you should probably instruct people how to do it in the correct, non-legacy way. :P

**Comment by jtdaugherty** [comment]
The trouble is, what constitutes "correct" or "non-legacy" is difficult to pin down because there is no telling what version of the `cabal` tool any given user will be running. :(

**Comment by jtdaugherty** [comment]
As far as the build step itself is concerned, though, `new-build` is the right way to go.
