### ISSUE TITLE
Option to output simple codes rather than 256-color

### ISSUE THREAD

**Issue by LoganDark** [jtdaugherty/tart#15]
The `.color.txt`s outputted by tart are filled with `<ESC>[38;5;<index>m` codes, even when I choose simple colors like red or blue (the non-bright versions). Is there an option to output simple codes instead (30-37 rather than 38)?

**Comment by jtdaugherty** [comment]
No, there is not an option to control that behavior. If you are curious about playing around with it yourself, [here is the relevant spot](https://github.com/jtdaugherty/tart/blob/master/src/Tart/Canvas.hs#L225).
