### ISSUE TITLE
Resize canvas dialog interface issue

### ISSUE THREAD

**Issue by benjaminselfridge** [jtdaugherty/tart#5]
Took me a second to realize I *had* to use tab to access the different text boxes of the dialogs. Clicking with the mouse doesn't work for some reason. Also, it would be nice if you could "click out" of a dialog by clicking on the outer screen, essentially a close-on-defocus thing.

This isn't really a bug, more of an interface preference

**Comment by jtdaugherty** [comment]
Yeah, I didn't hook up any click handlers for that dialog. But it can be done easily. Thanks!
